project:
  type: website
  output-dir: docs

website:
  search: false
  navbar:
    left:
      - text: Hi!
        href: index.qmd
      - text: research
        href: research.qmd
      - text: outreach
        href: outreach.qmd
      - text: CV
        href: cv.qmd
      - text: courses.qmd
        href: courses



format:
  html:
    theme: yeti
      # light: yeti
      # dark: [yeti, theme-dark.scss]
    css: styles.css
    toc: true

# https://github.com/cgoo4/quantumjitter


